nextify/apps/operation/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^create/$', login_required(views.OperationCreate.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.OperationUpdate.as_view()), name='update'),
    url(r'^$', login_required(views.OperationList.as_view()), name='list'),
    url(r'^lookup/$', views.OperationLookupView.as_view(), name='lookup'),
    url(r'^json/$', login_required(views.OperationListJson.as_view()), name='list-json'),
]

nextify_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^location/', include('nextify.externals.tables.location.urls', namespace='location')),
    url(r'^ncm/', include('nextify.externals.tables.ncm.urls', namespace='ncm')),
    url(r'^cfop/', include('nextify.externals.tables.cfop.urls', namespace='cfop')),
    url(r'^customer/', include('nextify.apps.person.customer.urls', namespace='customer')),
    url(r'^supplier/', include('nextify.apps.person.supplier.urls', namespace='supplier')),
    url(r'^shippingcompany/', include('nextify.apps.person.shippingcompany.urls', namespace='shippingcompany')),
    url(r'^address/', include('nextify.apps.address.urls', namespace='address')),
#    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^product/', include('nextify.apps.catalogue.product.urls', namespace='product')),
    url(r'^pricing/', include('nextify.apps.pricing.urls', namespace='pricing')),
    url(r'^unit/', include('nextify.apps.unit.urls', namespace='unit')),
    url(r'^itemcategory/', include('nextify.apps.catalogue.itemcategory.urls', namespace='itemcategory')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^payment/', include('nextify.apps.payment.urls', namespace='payment')),
    url(r'^nfe/', include('nextify.apps.document.nfe.urls', namespace='nfe')),
    url(r'^nfce/', include('nextify.apps.document.nfce.urls', namespace='nfce')),
    url(r'^invoice/', include('nextify.apps.document.invoice.urls', namespace='invoice')),
    url(r'^api/', include('nextify.apps.document.urls', namespace='api')),
    url(r'^', login_required(TemplateView.as_view(template_name='blank.html'))),
    # Document


]

urlpatterns += staticfiles_urlpatterns()

nextify/apps/operation/models.py
from .abstract_models import AbstractOperation, AbstractOperationCategory, AbstractOperationNFe, AbstractOperationCfop


class Operation(AbstractOperation):
    pass


class OperationCategory(AbstractOperationCategory):
    pass


class OperationNFe(AbstractOperationNFe):
    pass


class OperationCfop(AbstractOperationCfop):
    pass

# class OperationTax(AbstractOperationTax):
#     pass

nextify/apps/operation/forms.py
# -*- coding: utf-8 -*-
import nextify.core.util.nextforms as forms
from django.forms.models import inlineformset_factory
from nextify.core.forms import NextifyBaseInlineFormSet
from nextify.core.util.crispy_forms.helper import FormHelper
from nextify.core.util.crispy_forms.layout import Layout, Submit, Field, Div, Row, HTML, NextifyInlineField
from nextify.core.util.crispy_forms.bootstrap import FormActions

from nextify.externals.tables.cfop.widgets import CfopSelect
from nextify.externals.tables.cfop.models import Cfop

from .models import Operation, OperationCfop


class OperationForm(forms.ModelForm):
    helper = FormHelper()
    helper.form_tag = False
    helper.layout = Layout(
        Div(
            HTML(u'<h3 class="form-section">Informações da Operação</h3>'),
            Row(
                Div(Field('code', css_class='form-control'), css_class='col-md-6'),
                Div(Field('description', css_class='form-control'), css_class='col-md-6'),
            ),
            Row(
                Div(Field('operation_category', css_class='form-control'), css_class='col-md-3'),
                Div(Field('operation_type', css_class='form-control'), css_class='col-md-3'),
                Div(Field('issuer_type', css_class='form-control'), css_class='col-md-3'),
                Div(Field('model', css_class='form-control'), css_class='col-md-3'),
            ),
            css_class='form-body',
        ),
    )

    class Meta:
        model = Operation
        fields = ['code', 'description', 'operation_type', 'operation_category', 'issuer_type', 'model', ]


class OperationCfopForm(forms.ModelForm):
    cfop = forms.ModelChoiceField(label=u'CFOP', widget=CfopSelect(),
                                                queryset=Cfop.objects.all())

    class Meta:
        model = OperationCfop
        fields = ['cfop',]

OperationCfopFormSet = inlineformset_factory(Operation, OperationCfop, form=OperationCfopForm, min_num=0, extra=1,
                                             formset=NextifyBaseInlineFormSet, fields=['cfop',])


class OperationCfopInlineHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(OperationCfopInlineHelper, self).__init__(*args, **kwargs)
        self.form_tag = False
        self.form_id = 'operationcfop'
        self.form_show_labels = False
        self.disable_csrf = True
        self.render_required_fields = True
        self.render_hidden_fields = True
        self.layout = Layout(
            Row(
                NextifyInlineField('DELETE'),
                NextifyInlineField('cfop', wrapper_class='col-md-12'),
            ),
        )

nextify/apps/operation/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponseRedirect
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse
from django.db.models import Q

from nextify.core.views.generic import ObjectLookupView
from nextify.apps.operation.models import Operation
from nextify.core.views.datatables import BaseDatatableView
from . import forms


class OperationCreate(SuccessMessageMixin, CreateView):
    model = Operation
    form_class = forms.OperationForm
    success_message = u'Operação cadastrada com sucesso.'

    def get_success_url(self):
        if 'save' in self.request.POST:
            return reverse('operation:update', kwargs={'pk': self.object.pk, })
        if 'save-add' in self.request.POST:
            return reverse('operation:create')


class OperationUpdate(SuccessMessageMixin, UpdateView):
    model = Operation
    form_class = forms.OperationForm
    success_message = u'Operação atualizada com sucesso.'

    def get_success_url(self):
        if 'save' in self.request.POST:
            return reverse('operation:update', kwargs={'pk': self.object.pk, })
        if 'save-add' in self.request.POST:
            return reverse('operation:create')

    def get_context_data(self, **kwargs):
        context = super(OperationUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = forms.OperationForm(self.request.POST, instance=self.object)
            context['cfopformset'] = forms.OperationCfopFormSet(self.request.POST, instance=self.object)
            context['cfopformset_helper'] = forms.OperationCfopInlineHelper()

        else:
            context['form'] = forms.OperationForm(instance=self.object)
            context['cfopformset'] = forms.OperationCfopFormSet(instance=self.object)
            context['cfopformset_helper'] = forms.OperationCfopInlineHelper()
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        cfopformset = forms.OperationCfopFormSet(self.request.POST, instance=self.object)
        if form.is_valid() and cfopformset.is_valid():
            return self.form_valid(form, cfopformset)
        else:
            return self.form_invalid(form, cfopformset)

    def form_valid(self, form, cfopformset):
        self.object = form.save()
        cfopformset.instance = self.object
        cfopformset.save()
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, cfopformset):
        return self.render_to_response(
            self.get_context_data(form=form, cfopformset=cfopformset,
                                  cfopformset_helper=forms.OperationCfopInlineHelper())
        )


class OperationLookupView(ObjectLookupView):
    model = Operation

    def lookup_filter(self, qs, term):
        return qs.filter(Q(code__istartswith=term) | Q(description__icontains=term))


class OperationList(ListView):
    model = Operation


class OperationListJson(BaseDatatableView):
    model = Operation
    columns = ['id', 'code', 'description', 'edit']
    order_columns = ['id', 'code', 'description']

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500

    # def filter_queryset(self, qs):
    #     search_values = self.get_search_values()
    #     cols = self.get_columns()
    #     for i in range(len(search_values)):
    #         if search_values[i] != '':
    #             if cols[i] == 'name':
    #                 qs = qs.filter(name__icontains=search_values[i])
    #             if cols[i] == 'category':
    #                 qs = qs.filter(category__exact=search_values[i])
    #             if cols[i] == 'is_active':
    #                 qs = qs.filter(is_active=str2bool(search_values[i]))
    #
    #     return qs
    #
    # def get_initial_queryset(self, company=None):
    #     return super(CustomerListViewJson, self).get_initial_queryset(get_logged_company(self.request))

templates/operation/operation_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}
{% load crispy_forms_tags %}

{% block content %}
<div class="portlet light bordered">
    <div class="portlet-title tabbable-line">
        <div class="caption">
            <i class="icon-basket"></i>
            {% if object.id %}
            <span class="caption-subject font-blue-ebonyclay sbold">Atualizar Operação #{{ object.code }} | {{ object.description }}</span>
            {% else %}
            <span class="caption-subject font-blue-ebonyclay sbold">Cadastro de Operação </span>
            {% endif %}
        </div>
            <ul class="nav nav-tabs">
                {% if object.id %}
                <li>
                    <a href="#portlet_tab_cfop" data-toggle="tab"> CFOP </a>
                </li>
                {% endif %}
                <li class="active">
                    <a href="#portlet_tab_general" data-toggle="tab"> Informações Gerais </a>
                </li>
            </ul>
        </div>
        <div class="portlet-body form">
            <form method="post" >
                <div class="tab-content">
                    <div class="tab-pane active" id="portlet_tab_general">
                        {% crispy form %}
                    </div>
                    {% if object.id %}
                    <div class="tab-pane" id="portlet_tab_cfop">
                        {{ cfopformset.management_form }}
                        <h4 class="form-section">Listagem de CFOP</h4>
                        <div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
                            <a id="tab_images_uploader_pickfiles" href="javascript:;" class="btn btn-success add-cfop">
                            <i class="fa fa-plus"></i> Incluir CFOP </a>
                        </div>
                        <div class="row"><div id="tab_images_uploader_filelist" class="col-md-6 col-sm-12"></div></div>
                        {% include 'metronic/table_inline_formset_nextify.html' with formset=cfopformset helper=cfopformset_helper %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="submit" name="save" value="Salvar" class="btn btn-primary btn green" id="submit-id-submit"/>
                                    <input type="submit" name="save-add" value="Salvar e Cadastrar um novo" class="btn btn-primary btn blue-hoki" id="submit-id-submit"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>

            </form>
        </div>
</div>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
<script src={% static "assets/pages/scripts/form-samples.min.js" %} type="text/javascript"></script>
    {% if object.id %}
    <script src={% static "assets/apps/nextify/scripts/operation/operation.form.js" %} type="text/javascript"></script>
    <script type="text/html" id="cfop_template">
    {% include 'metronic/table_inline_formset_nextify_empty.html' with form=cfopformset.empty_form helper=cfopformset_helper %}
    </script>
{% endif %}
{% endblock %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/select2/select2.css" %} rel="stylesheet" type="text/css"/>
<link href={% static "assets/global/plugins/select2/select2-bootstrap.css" %} rel="stylesheet" type="text/css"/>
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script type="text/javascript" src={% static "assets/global/plugins/select2/select2.min.js" %}></script>
{% endblock %}

templates/operation/operation_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}

{% block content %}
<!-- Begin: life time stats -->
<!-- Begin: life time stats -->
<div class="portlet light portlet-fit portlet-datatable bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body">
        <div class="table-container">
            <div class="table-actions-wrapper">
                <span>
                </span>
                <div class="actions">
                    <a href="{% url 'operation:create' %}" class="btn btn-sm btn-info">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar Operação </span>
                    </a>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover" id="default_datatable" ajax-url="{% url 'operation:list-json' %}">
            <thead>
                <tr role="row" class="heading">
                    <th width="1%">#</th>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th width="5%"></th>

                </tr>
            </thead>
            <tbody>
            </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End: life time stats -->
{% endblock content %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/datatables/datatables.min.css" %} rel="stylesheet" type="text/css" />
<link href={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
{% endblock %}