nextify/apps/document/invoice/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^create/$', login_required(views.InvoiceCreateView.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.InvoiceUpdateView.as_view()), name='update'),
    url(r'^$', login_required(views.InvoiceList.as_view()), name='list'),
    url(r'^json/$', login_required(views.InvoiceListViewJson.as_view()), name='list-json'),
    url(r'^(?P<pk>[\w]+)/pdf/$', login_required(views.BoletoPDFAll.as_view()), name='invoice-pdf'),
    url(r'^(?P<pk>[\w]+)/duplicate/pdf/$', login_required(views.BoletoPDF.as_view()), name='duplicate-pdf'),

    # BankFile
    url(r'^bankfile/$', login_required(views.BankFileList.as_view()), name='bankfile-list'),
    url(r'^bankfile/create/$', login_required(views.BankFileCreateView.as_view()), name='bankfile-create'),
    url(r'^bankfile/json/$', login_required(views.BankFileListViewJson.as_view()), name='bankfile-list-json'),
    url(r'^bankfile/(?P<pk>[\w]+)/generate/$', login_required(views.BankFileSelectOcurrences.as_view()), name='bankfile-generate'),
    url(r'^bankfile/(?P<pk>[\w]+)/dowload/$', login_required(views.BankFileDownload.as_view()), name='bankfile-download'),
]

nextify/apps/document/nfce/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^issue/$', login_required(views.NFeIssue.as_view()), name='issue'),
    url(r'^create/$', login_required(views.NFeCreateRedirect.as_view()), name='create'),
    url(r'^send/$', login_required(views.NFeSendQueryUpdate.as_view()), name='send-query'),

    url(r'^in/create/(?P<operation_pk>[\w]+)/$', login_required(views.NFeInCreate.as_view()), name='in-create'),
    url(r'^out/create/(?P<operation_pk>[\w]+)/$', login_required(views.NFeOutCreate.as_view()), name='out-create'),
    url(r'^(?P<pk>[\w]+)/in/update/$', login_required(views.NFeInUpdateView.as_view()), name='in-update'),
    url(r'^(?P<pk>[\w]+)/out/update/$', login_required(views.NFeOutUpdateView.as_view()), name='out-update'),
    url(r'^(?P<pk>[\w]+)/finalize/$', login_required(views.NFeUpdateFinalize.as_view()), name='finalize'),
    url(r'^(?P<pk>[\w]+)/in/line/update/$', login_required(views.NFeInLineUpdate.as_view()), name='in-line-update'),
    url(r'^(?P<pk>[\w]+)/out/line/update/$', login_required(views.NFeOutLineUpdate.as_view()), name='out-line-update'),
    url(r'^(?P<pk>[\w]+)/danfe/$', login_required(views.NFePdfDANFE.as_view()), name='danfe'),

    url(r'^third/$', login_required(views.NFeListThird.as_view()), name='list-third'),
    url(r'^self/$', login_required(views.NFeListSelf.as_view()), name='list-self'),
    url(r'^json/third/$', login_required(views.NFeListThirdJson.as_view()), name='list-third-json'),
    url(r'^json/self/$', login_required(views.NFeListSelfJson.as_view()), name='list-self-json'),

    # Eventos
    url(r'^event/$', login_required(views.NFeEventCreateRedirect.as_view()), name='event'),
    url(r'^(?P<nfe_pk>[\w]+)/cancel/$', login_required(views.NFeCancelCreate.as_view()), name='cancel'),
    url(r'^(?P<pk>[\w]+)/cancel/confirm/$', login_required(views.NFeCancelUpdate.as_view()), name='cancel-confirm'),
    url(r'^(?P<nfe_pk>[\w]+)/cce/$', login_required(views.NFeCceCreate.as_view()), name='cce'),
    url(r'^(?P<pk>[\w]+)/cce/confirm/$', login_required(views.NFeCceUpdate.as_view()), name='cce-confirm'),

    # API
    url(r'^nfce_api/(?P<pk>[\w]+)/$', views.APINFe.as_view(), name='api_nfce'),
]

nextify/apps/document/nfe/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required
from . import views
from rest_serializer import nfe_list

urlpatterns = [
    url(r'^issue/$', login_required(views.NFeIssue.as_view()), name='issue'),
    url(r'^create/$', login_required(views.NFeCreateRedirect.as_view()), name='create'),
    url(r'^send/$', login_required(views.NFeSendQueryUpdate.as_view()), name='send-query'),

    url(r'^in/create/(?P<operation_pk>[\w]+)/$', login_required(views.NFeInCreate.as_view()), name='in-create'),
    url(r'^out/create/(?P<operation_pk>[\w]+)/$', login_required(views.NFeOutCreate.as_view()), name='out-create'),
    url(r'^(?P<pk>[\w]+)/in/update/$', login_required(views.NFeInUpdateView.as_view()), name='in-update'),
    url(r'^(?P<pk>[\w]+)/out/update/$', login_required(views.NFeOutUpdateView.as_view()), name='out-update'),
    url(r'^(?P<pk>[\w]+)/finalize/$', login_required(views.NFeUpdateFinalize.as_view()), name='finalize'),
    url(r'^(?P<pk>[\w]+)/in/line/update/$', login_required(views.NFeInLineUpdate.as_view()), name='in-line-update'),
    url(r'^(?P<pk>[\w]+)/out/line/update/$', login_required(views.NFeOutLineUpdate.as_view()), name='out-line-update'),
    url(r'^(?P<pk>[\w]+)/danfe/$', login_required(views.NFePdfDANFE.as_view()), name='danfe'),

    url(r'^third/$', login_required(views.NFeListThird.as_view()), name='list-third'),
    url(r'^self/$', login_required(views.NFeListSelf.as_view()), name='list-self'),
    url(r'^json/third/$', login_required(views.NFeListThirdJson.as_view()), name='list-third-json'),
    url(r'^json/self/$', login_required(views.NFeListSelfJson.as_view()), name='list-self-json'),

    # Eventos
    url(r'^event/$',  login_required(views.NFeEventCreateRedirect.as_view()), name='event'),
    url(r'^(?P<nfe_pk>[\w]+)/cancel/$', login_required(views.NFeCancelCreate.as_view()), name='cancel'),
    url(r'^(?P<pk>[\w]+)/cancel/confirm/$', login_required(views.NFeCancelUpdate.as_view()), name='cancel-confirm'),
    url(r'^(?P<nfe_pk>[\w]+)/cce/$', login_required(views.NFeCceCreate.as_view()), name='cce'),
    url(r'^(?P<pk>[\w]+)/cce/confirm/$', login_required(views.NFeCceUpdate.as_view()), name='cce-confirm'),

    # url(r'^api/$', nfe_list),
]

nextify/apps/document/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from serializer import NFeQueueList, NFeQueueDetail, NFeWsStatusDetail

urlpatterns = [
    url(r'^nfe/$', NFeQueueList.as_view()),
    url(r'^nfe/(?P<pk>[0-9]+)/$', NFeQueueDetail.as_view()),
    url(r'^nfestatusservico/$', NFeWsStatusDetail.as_view()),
]

nextify/apps/unit/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views

urlpatterns = [
    url(r'^create/$', login_required(views.UnitCreate.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.UnitUpdate.as_view()), name='update'),
    url(r'^$', login_required(views.UnitList.as_view()), name='list'),
    url(r'^json/$', login_required(views.UnitListJson.as_view()), name='list-json'),
    url(r'^lookup/$', login_required(views.UnitLookupView.as_view()), name='lookup'),
]

nextify_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^location/', include('nextify.externals.tables.location.urls', namespace='location')),
    url(r'^ncm/', include('nextify.externals.tables.ncm.urls', namespace='ncm')),
    url(r'^cfop/', include('nextify.externals.tables.cfop.urls', namespace='cfop')),
    url(r'^customer/', include('nextify.apps.person.customer.urls', namespace='customer')),
    url(r'^supplier/', include('nextify.apps.person.supplier.urls', namespace='supplier')),
    url(r'^shippingcompany/', include('nextify.apps.person.shippingcompany.urls', namespace='shippingcompany')),
    url(r'^address/', include('nextify.apps.address.urls', namespace='address')),
#    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^product/', include('nextify.apps.catalogue.product.urls', namespace='product')),
    url(r'^pricing/', include('nextify.apps.pricing.urls', namespace='pricing')),
    url(r'^unit/', include('nextify.apps.unit.urls', namespace='unit')),
    url(r'^itemcategory/', include('nextify.apps.catalogue.itemcategory.urls', namespace='itemcategory')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^payment/', include('nextify.apps.payment.urls', namespace='payment')),
    url(r'^nfe/', include('nextify.apps.document.nfe.urls', namespace='nfe')),
    url(r'^nfce/', include('nextify.apps.document.nfce.urls', namespace='nfce')),
    url(r'^invoice/', include('nextify.apps.document.invoice.urls', namespace='invoice')),
    url(r'^api/', include('nextify.apps.document.urls', namespace='api')),
    url(r'^', login_required(TemplateView.as_view(template_name='blank.html'))),
    # Document


]

urlpatterns += staticfiles_urlpatterns()

nextify/apps/document/nfse/models.py
from django.db import models

# Create your models here.

nextify/apps/document/invoice/views.py
# -*- coding: utf-8 -*-
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib import messages
from django.views.generic import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse
from django.views.generic import RedirectView, DetailView
from django.http import HttpResponseRedirect, HttpResponse
from nextify.apps.document.invoice.models import Invoice, InvoiceDuplicate, BankFile
from nextify.apps.document.invoice import forms

from nextify.core.views.datatables import BaseDatatableView
from nextify.core.views.generic import ObjectLookupView


class InvoiceListViewJson(BaseDatatableView):
    columns = ['id', 'bank', 'invoice_number', 'net_value', 'child', 'edit']
    order_columns = ['id', 'bank', 'invoice_number', 'net_value']
    model = Invoice

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500

    def render_column(self, row, column):
        """ Renders a column on a row
        """
        if column == 'child':
            text = 'Boletos'
            return text
        if column == 'child':
            return '<a href="%s" class="btn btn-sm btn-default btn-circle btn-editable"><i class="fa fa-pencil">' \
                   '</i> %s</a>' % (row.get_absolute_url(), "Listar Parcelas")

        return super(InvoiceListViewJson, self).render_column(row, column)


class InvoiceCreateView(SuccessMessageMixin, CreateView):
    model = Invoice
    form_class = forms.InvoiceForm
    success_message = 'Fatura cadastrada com sucesso.'
    template_name = 'document/invoice/invoice_form.html'

    valid_dict = {
        'form': 'active',
        'formset_duplicates': ''
    }

    def get_success_url(self):
        return reverse('invoice:update', kwargs={'pk': self.object.pk, })

    def get_context_data(self, **kwargs):
        context = super(InvoiceCreateView, self).get_context_data(**kwargs)
        context['active'] = self.valid_dict
        return context


class InvoiceUpdateView(SuccessMessageMixin, UpdateView):
    model = Invoice
    form_class = forms.InvoiceForm
    success_message = 'Fatura atualizada com sucesso.'
    template_name = 'document/invoice/invoice_form.html'
    formset_invoiceduplicates = forms.InvoiceDuplicateFormSet

    valid_dict = {
        'form': 'active',
        'formset_duplicates': ''
    }

    def get_success_url(self):
        return reverse('invoice:update', kwargs={'pk': self.object.pk, })

    def get_context_data(self, **kwargs):
        context = super(InvoiceUpdateView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = self.form_class(self.request.POST, instance=self.object)
            context['formset_duplicates'] = self.formset_invoiceduplicates(self.request.POST, instance=self.object)
            context['invoiceduplicates_helper'] = forms.InvoiceDuplicateFormInlineHelper()
        else:
            self.valid_dict['form'] = 'active'
            self.valid_dict['formset_duplicates'] = ''
            context['form'] = self.form_class(instance=self.object)
            context['formset_duplicates'] = self.formset_invoiceduplicates(instance=self.object)
            context['invoiceduplicates_helper'] = forms.InvoiceDuplicateFormInlineHelper()
        context['active'] = self.valid_dict
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_duplicates = self.formset_invoiceduplicates(self.request.POST, instance=self.object)
        if self.valid_forms(form, formset_duplicates):
            return self.form_valid(form, formset_duplicates)
        else:
            return self.form_invalid(form, formset_duplicates)

    def form_valid(self, form, formset_duplicates):
        self.object = form.save()
        formset_duplicates.instance = self.object
        formset_duplicates.save()
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset_duplicates):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  formset_duplicates=formset_duplicates,
                                  invoiceduplicates_helper=forms.InvoiceDuplicateFormInlineHelper(),
                                  )
        )

    def valid_forms(self, form, formset_duplicates):
        self.valid_dict['form'] = ''
        self.valid_dict['formset_duplicates'] = ''
        if not form.is_valid():
            self.valid_dict['form'] = 'active'
        elif not formset_duplicates.is_valid():
            self.valid_dict['formset_duplicates'] = 'active'
        else:
            self.valid_dict['form'] = 'active'
            return True
        return False


class InvoiceList(ListView):
    model = Invoice
    template_name = 'document/invoice/invoice_list.html'


class BoletoPDF(DetailView):
    model = InvoiceDuplicate

    def render_to_response(self, context, **response_kwargs):
        from .bank_process import BankServices

        pk = self.kwargs.get('pk')
        duplicate = InvoiceDuplicate.on_company.get(pk=pk)
        b = BankServices()
        b.duplicate = duplicate
        b.process()
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="%s.pdf"' % 'boleto'
        response.content = b.gerar_boleto()

        return response


class BoletoPDFAll(DetailView):
    model = Invoice

    def render_to_response(self, context, **response_kwargs):
        from .bank_process import BankServices

        pk = self.kwargs.get('pk')
        invoice = Invoice.on_company.get(pk=pk)
        b = BankServices()
        b.invoice = invoice
        b.process()
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = 'attachment; filename="%s.pdf"' % 'boleto'
        response.content = b.gerar_boleto()

        return response

class BankFileListViewJson(BaseDatatableView):
    columns = ['id', 'file_name', 'file']
    order_columns = ['id', 'file_name']
    model = BankFile

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500

    def render_column(self, row, column):
        """ Renders a column on a row
        """
        if column == 'file':
            return '<a href="%s" class="btn btn-sm btn-default btn-circle btn-editable"><i class="fa fa-pencil">' \
                   '</i> %s</a>' % (row.get_bankfile_url(), "Gerar Arquivo")

        return super(BankFileListViewJson, self).render_column(row, column)


class BankFileCreateView(SuccessMessageMixin, CreateView):
    model = BankFile
    form_class = forms.BankFileForm
    success_message = 'Remessa cadastrada com sucesso.'
    template_name = 'document/invoice/bankfile_form.html'

    def get_success_url(self):
        return reverse('invoice:bankfile-list')


class BankFileList(ListView):
    model = BankFile
    template_name = 'document/invoice/bankfile_list.html'


class BankFileSelectOcurrences(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        pk = self.kwargs.get('pk')
        file = BankFile.on_company.get(pk=pk)
        file.select_ocurrences_to_file()
        return reverse('invoice:bankfile-list')


class BankFileDownload(DetailView):
    model = BankFile

    def render_to_response(self, context, **response_kwargs):
        from .bank_process import BankServices

        pk = self.kwargs.get('pk')
        bank_file = BankFile.on_company.get(pk=pk)
        b = BankServices()
        b.bank_file = bank_file
        b.process()
        response = HttpResponse(content_type='text/html; charset=utf-8')
        response['Content-Disposition'] = 'attachment; filename="%s.txt"' % 'boleto'
        response.content = b.generate_bankfile()

        return response

nextify/apps/document/nfse/views.py
from django.shortcuts import render

# Create your views here.

nextify/apps/document/views.py
from django.shortcuts import render
from django.views.generic import RedirectView
from django.core.urlresolvers import reverse
# Create your views here.


class NFeSendQueryUpdate(RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        #send_nfe()
        return reverse('nfe:list-self')

    def query_nfe(self):
        pass

templates/document/invoice/bankfile_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}
{% load crispy_forms_tags %}

{% block content %}
<div class="portlet light bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body form">
        {% crispy form %}
    </div>
</div>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
<script src={% static "assets/pages/scripts/form-samples.min.js" %} type="text/javascript"></script>
{% endblock %}

templates/document/invoice/bankfile_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}

{% block content %}
<!-- Begin: life time stats -->
<!-- Begin: life time stats -->
<div class="portlet light portlet-fit portlet-datatable bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body">
        <div class="table-container">
            <div class="table-actions-wrapper">
                <span>
                </span>
                <div class="actions">
                    <a href="{% url 'invoice:bankfile-create' %}" class="btn btn-sm btn-info">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar Remessa </span>
                    </a>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover" id="default_datatable" ajax-url="{% url 'invoice:bankfile-list-json' %}">
            <thead>
                <tr role="row" class="heading">
                    <th width="1%">#</th>
                    <th>Arquivo</th>
                    <th width="5%"></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End: life time stats -->
{% endblock content %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/datatables/datatables.min.css" %} rel="stylesheet" type="text/css" />
<link href={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
{% endblock %}

templates/document/invoice/invoice_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load dictionary %}

{% block content %}
<div class="portlet light bordered">
    <div class="portlet-title tabbable-line">
        <div class="caption">
            <i class="icon-basket"></i>
            {% if object.id %}
            <span class="caption-subject font-blue-ebonyclay sbold">Atualizar Fatura #{{ object.invoice_number }}</span>
            {% else %}
            <span class="caption-subject font-blue-ebonyclay sbold">Cadastro de Fatura </span>
            {% endif %}
        </div>
        <ul class="nav nav-tabs">
            {% if object.id %}
            <li class="{{ active|get_item:'formset_duplicates' }}">
                <a href="#portlet_tab_duplicates" data-toggle="tab"> Parcelas </a>
            </li>
            {% endif %}
            <li class="{{ active|get_item:'form' }}">
                <a href="#portlet_tab_general" data-toggle="tab"> Fatura </a>
            </li>
        </ul>
    </div>
    <div class="portlet-body form">
        <form method="post" >
            <div class="tab-content">
                <div class="tab-pane {{ active|get_item:'form' }}" id="portlet_tab_general">
                    {% crispy form %}
                </div>
                {% if object.id %}
                <input type="hidden" value="{{ object.id }}" id="product_id">
                <div class="tab-pane {{ active|get_item:'formset_duplicates' }}" id="portlet_tab_duplicates">
                    {{ formset_duplicates.management_form }}
                    <h4 class="form-section">Listagem de Parcelas</h4>
                    <div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
                        <a id="tab_images_uploader_pickfiles" href="javascript:;" class="btn btn-success add-duplicate">
                        <i class="fa fa-plus"></i> Incluir Parcela </a>
                    </div>
                    <div class="row"><div id="tab_images_uploader_filelist" class="col-md-6 col-sm-12"></div></div>
                    {% include 'metronic/table_inline_formset_nextify.html' with formset=formset_duplicates helper=invoiceduplicates_helper %}
                </div>
                {% endif %}
            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-6">
                        <div class="row">
                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" name="submit" value="Salvar" class="btn btn-primary btn green" id="submit-id-submit"/>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-md-6"></div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script type="text/javascript" src={% static "assets/global/plugins/select2/select2.min.js" %}></script>
<script src={% static "assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js" %} type="text/javascript"></script>
{% if object.id %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endif %}
<script src={% static "assets/global/plugins/jquery-inputmask/jquery.inputmask.bundle.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/select2/select2.css" %} rel="stylesheet" type="text/css"/>
<link href={% static "assets/global/plugins/select2/select2-bootstrap.css" %} rel="stylesheet" type="text/css"/>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
<script src={% static "assets/pages/scripts/form-samples.min.js" %} type="text/javascript"></script>
<script src={% static "assets/apps/nextify/scripts/document/invoice/invoice.js" %} type="text/javascript"></script>
{% if object.id %}
<script type="text/html" id="invoiceduplicate_template">
{% include 'metronic/table_inline_formset_nextify_empty.html' with form=formset_duplicates.empty_form helper=invoiceduplicates_helper %}
</script>
{% endif %}
{% endblock %}

templates/document/invoice/invoice_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}

{% block content %}
<!-- Begin: life time stats -->
<!-- Begin: life time stats -->
<div class="portlet light portlet-fit portlet-datatable bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body">
        <div class="table-container">
            <div class="table-actions-wrapper">
                <span>
                </span>
                <div class="actions">
                    <a href="{% url 'invoice:create' %}" class="btn btn-sm btn-info">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar Fatura </span>
                    </a>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover" id="default_datatable" ajax-url="{% url 'invoice:list-json' %}">
            <thead>
                <tr role="row" class="heading">
                    <th width="1%">#</th>
                    <th>Código</th>
                    <th>Número</th>
                    <th>Valor</th>
                    <th></th>
                    <th width="5%"></th>
                </tr>
            </thead>
            <tbody>
            </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End: life time stats -->
{% endblock content %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/datatables/datatables.min.css" %} rel="stylesheet" type="text/css" />
<link href={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
{% endblock %}