nextify/apps/catalogue/itemcategory/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^create/$', login_required(views.ItemCategoryCreate.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.ItemCategoryUpdate.as_view()), name='update'),
    url(r'^$', login_required(views.ItemCategoryList.as_view()), name='list'),
    url(r'^json/$', login_required(views.ItemCategoryListJson.as_view()), name='list-json'),
]

nextify/apps/catalogue/product/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from . import views

urlpatterns = [
    url(r'^create/$', login_required(views.ProductCreate.as_view()), name='create'),
    url(r'^(?P<pk>\d+)/update/$', login_required(views.ProductUpdate.as_view()), name='update'),
    url(r'^$', login_required(views.ProductList.as_view()), name='list'),
    url(r'^json/$', login_required(views.ProductListJson.as_view()), name='list-json'),
    url(r'^lookup/$', login_required(views.ProductLookupView.as_view()), name='lookup'),
    url(r'^unit/lookup/$', login_required(views.ProductUnitLookupView.as_view()), name='unit-lookup'),
]

nextify_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^location/', include('nextify.externals.tables.location.urls', namespace='location')),
    url(r'^ncm/', include('nextify.externals.tables.ncm.urls', namespace='ncm')),
    url(r'^cfop/', include('nextify.externals.tables.cfop.urls', namespace='cfop')),
    url(r'^customer/', include('nextify.apps.person.customer.urls', namespace='customer')),
    url(r'^supplier/', include('nextify.apps.person.supplier.urls', namespace='supplier')),
    url(r'^shippingcompany/', include('nextify.apps.person.shippingcompany.urls', namespace='shippingcompany')),
    url(r'^address/', include('nextify.apps.address.urls', namespace='address')),
#    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^product/', include('nextify.apps.catalogue.product.urls', namespace='product')),
    url(r'^pricing/', include('nextify.apps.pricing.urls', namespace='pricing')),
    url(r'^unit/', include('nextify.apps.unit.urls', namespace='unit')),
    url(r'^itemcategory/', include('nextify.apps.catalogue.itemcategory.urls', namespace='itemcategory')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^operation/', include('nextify.apps.operation.urls', namespace='operation')),
    url(r'^payment/', include('nextify.apps.payment.urls', namespace='payment')),
    url(r'^nfe/', include('nextify.apps.document.nfe.urls', namespace='nfe')),
    url(r'^nfce/', include('nextify.apps.document.nfce.urls', namespace='nfce')),
    url(r'^invoice/', include('nextify.apps.document.invoice.urls', namespace='invoice')),
    url(r'^api/', include('nextify.apps.document.urls', namespace='api')),
    url(r'^', login_required(TemplateView.as_view(template_name='blank.html'))),
    # Document


]

urlpatterns += staticfiles_urlpatterns()

nextify/apps/catalogue/models.py
from .abstract_models import *
from .product.abstract_models import AbstractProduct, AbstractProductSupplier, AbstractProductUnits, \
    AbstractProductParameters
from .service.abstract_models import AbstractService
from .itemcategory.abstract_models import *

class Item(AbstractItem):
    pass

class ItemCategory(AbstractItemCategory):
    pass

class Product(Item, AbstractProduct):
    pass

class ProductSupplier(AbstractProductSupplier):
    pass

class ProductUnits(AbstractProductUnits):
    pass

class ProductParameters(AbstractProductParameters):
    pass

class Service(Item, AbstractService):
    pass

nextify/apps/catalogue/itemcategory/forms.py
# -*- coding: utf-8 -*-
#from django import forms
import nextify.core.util.nextforms as forms
from nextify.core.util.crispy_forms.helper import FormHelper
from nextify.core.util.crispy_forms.layout import Layout, Submit, Field, Div, Row, Colmd6, Colmd3, HTML, Coloff1md2
from nextify.core.util.crispy_forms.bootstrap import FormActions

from nextify.apps.catalogue.models import ItemCategory

class ItemCategoryForm(forms.ModelForm):

    helper = FormHelper()

    helper.layout = Layout(
        Div(
            HTML(u'<h3 class="form-section">Informações da Categoria</h3>'),
            Row(
                Colmd6(Field('code', readonly=True)),
                Colmd6(Field('description')),
            ),
            Row(
                Colmd6(Field('genre', css_class='form-control')),
            ),
            css_class='form-body',
        ),
        FormActions(Submit('submit', 'Salvar', css_class='btn green')),
    )

    class Meta:
        model = ItemCategory

        fields = ['code', 'description', 'genre']

nextify/apps/catalogue/itemcategory/views.py
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse

from nextify.apps.catalogue.models import ItemCategory
from nextify.core.views.datatables import BaseDatatableView

from .forms import ItemCategoryForm

class ItemCategoryCreate(SuccessMessageMixin, CreateView):
    model = ItemCategory
    form_class = ItemCategoryForm
    success_message = 'Categoria de Produto cadastrada com sucesso.'

    def get_success_url(self):
        return reverse('itemcategory:update', kwargs={'pk': self.object.pk, })



class ItemCategoryUpdate(SuccessMessageMixin, UpdateView):
    model = ItemCategory
    form_class = ItemCategoryForm
    success_message = 'Categoria de Produto atualizada com sucesso.'

    def get_success_url(self):
        return reverse('itemcategory:update', kwargs={'pk': self.object.pk, })


class ItemCategoryList(ListView):
    model = ItemCategory


class ItemCategoryListJson(BaseDatatableView):
    model = ItemCategory
    columns = ['id', 'code', 'description', 'edit']
    order_columns = ['id', 'code', 'description']

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500

    # def filter_queryset(self, qs):
    #     search_values = self.get_search_values()
    #     cols = self.get_columns()
    #     for i in range(len(search_values)):
    #         if search_values[i] != '':
    #             if cols[i] == 'name':
    #                 qs = qs.filter(name__icontains=search_values[i])
    #             if cols[i] == 'category':
    #                 qs = qs.filter(category__exact=search_values[i])
    #             if cols[i] == 'is_active':
    #                 qs = qs.filter(is_active=str2bool(search_values[i]))
    #
    #     return qs
    #
    # def get_initial_queryset(self, company=None):
    #     return super(CustomerListViewJson, self).get_initial_queryset(get_logged_company(self.request))

nextify/apps/catalogue/product/views.py
import json
from itertools import chain
from django.http import HttpResponse, HttpResponseRedirect
from django.db.models import Q
from django.views.generic.edit import CreateView, UpdateView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.list import ListView
from django.core.urlresolvers import reverse

from nextify.apps.catalogue.models import Product, ProductUnits
from nextify.apps.unit.models import Unit
from nextify.core.views.datatables import BaseDatatableView
from nextify.core.views.generic import ObjectLookupView

from .forms import *
#from .forms import ProductForm, ProductSupplierFormSet, ProductSupplierInlineHelper


class ProductCreate(SuccessMessageMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_message = 'Produto cadastrado com sucesso.'

    valid_dict = {
        'form': 'active',
        'formset_suppliers': '',
        'formset_pricing': ''
    }

    def get_success_url(self):
        return reverse('product:update', kwargs={'pk': self.object.pk, })

    def get_context_data(self, **kwargs):
        context = super(ProductCreate, self).get_context_data(**kwargs)
        context['active'] = self.valid_dict
        return context


class ProductUpdate(UpdateView):
    model = Product
    form_class = ProductForm
    formset_suppliers = ProductSupplierFormSet
    formset_pricing = PriceTableLineFormSet
    success_message = 'Produto atualizado com sucesso!'

    valid_dict = {
        'form': '',
        'formset_suppliers': '',
        'formset_pricing': ''
    }

    def get_success_url(self):
        return reverse('product:update', kwargs={'pk': self.object.pk, })

    def get_context_data(self, **kwargs):
        context = super(ProductUpdate, self).get_context_data(**kwargs)
        if self.request.POST:
            context['form'] = self.form_class(self.request.POST, instance=self.object)
            context['formset_suppliers'] = self.formset_suppliers(self.request.POST, instance=self.object)
            context['formset_pricing'] = self.formset_pricing(self.request.POST, instance=self.object)
            context['suppliers_helper'] = ProductSupplierInlineHelper()
            context['pricing_helper'] = PriceTableLineInlineHelper()
        else:
            self.valid_dict['form'] = 'active'
            self.valid_dict['formset_suppliers'] = ''
            self.valid_dict['formset_pricing'] = ''
            context['form'] = self.form_class(instance=self.object)
            context['formset_suppliers'] = self.formset_suppliers(instance=self.object)
            context['formset_pricing'] = self.formset_pricing(instance=self.object)
            context['suppliers_helper'] = ProductSupplierInlineHelper()
            context['pricing_helper'] = PriceTableLineInlineHelper()
        context['active'] = self.valid_dict
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset_suppliers = self.formset_suppliers(self.request.POST, instance=self.object)
        formset_pricing = self.formset_pricing(self.request.POST, instance=self.object)
        if self.valid_forms(form, formset_suppliers, formset_pricing):
            return self.form_valid(form, formset_suppliers, formset_pricing)
        else:
            return self.form_invalid(form, formset_suppliers, formset_pricing)

    def form_valid(self, form, formset_suppliers, formset_pricing):
        self.object = form.save()
        formset_suppliers.instance = self.object
        formset_pricing.instance = self.object
        formset_suppliers.save()
        formset_pricing.save()
        messages.add_message(self.request, messages.SUCCESS, self.success_message)
        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset_suppliers, formset_pricing):
        return self.render_to_response(
            self.get_context_data(form=form,
                                  formset_suppliers=formset_suppliers,
                                  formset_pricing=formset_pricing,
                                  suppliers_helper=ProductSupplierInlineHelper(),
                                  pricing_helper=PriceTableLineInlineHelper(),
                                  )
        )

    def valid_forms(self, form, formset_suppliers, formset_pricing):
        self.valid_dict['form'] = ''
        self.valid_dict['formset_suppliers'] = ''
        self.valid_dict['formset_pricing'] = ''
        if not form.is_valid():
            self.valid_dict['form'] = 'active'
        elif not formset_suppliers.is_valid():
            self.valid_dict['formset_suppliers'] = 'active'
        elif not formset_pricing.is_valid():
            self.valid_dict['formset_pricing'] = 'active'
        else:
            self.valid_dict['form'] = 'active'
            return True
        return False


class ProductList(ListView):
    model = Product

class ProductListJson(BaseDatatableView):
    model = Product
    columns = ['id', 'code', 'description', 'stock_quantity_display', 'sales_price_display', 'edit']
    order_columns = ['id', 'code', 'description', 'stock_quantity_display', 'sales_price_display']
    search_columns = ['product_code', 'product_description']

    # set max limit of records returned, this is used to protect our site if someone tries to attack our site
    # and make it return huge amount of data
    max_display_length = 500

    def filter_queryset(self, qs):
        request = self.request
        for column in self.search_columns:
            try:
                value = request.POST.get(column, '')
                if column == 'product_description':
                    qs = qs.filter(description__icontains=value)
                if column == 'product_code':
                    qs = qs.filter(code__icontains=value)
            except ValueError:
                pass
        return qs

    # def filter_queryset(self, qs):
    #     search_values = self.get_search_values()
    #     cols = self.get_columns()
    #     for i in range(len(search_values)):
    #         if search_values[i] != '':
    #             if cols[i] == 'name':
    #                 qs = qs.filter(name__icontains=search_values[i])
    #             if cols[i] == 'category':
    #                 qs = qs.filter(category__exact=search_values[i])
    #             if cols[i] == 'is_active':
    #                 qs = qs.filter(is_active=str2bool(search_values[i]))
    #
    #     return qs
    #
    # def get_initial_queryset(self, company=None):
    #     return super(CustomerListViewJson, self).get_initial_queryset(get_logged_company(self.request))


class ProductLookupView(ObjectLookupView):
    model = Product

    def lookup_filter(self, qs, term):
        return qs.filter(Q(code__istartswith=term) | Q(description__icontains=term))


class ProductUnitLookupView(ObjectLookupView):
    model = Unit

    def lookup_filter(self, qs, term):
        return qs.filter(Q(code__istartswith=term) | Q(description__icontains=term))

    def get_args(self):
        GET = self.request.GET
        return (GET.get('initial', None),
                GET.get('q', None),
                GET.get('p', None),
                int(GET.get('page', 1)),
                int(GET.get('page_limit', 20)))

    def get(self, request):
        self.request = request
        qs = self.get_queryset()

        initial, q, p, page, page_limit = self.get_args()

        if initial:
            qs = self.initial_filter(qs, initial)
            more = False
        else:
            if p:
                prod = Product.on_company.get(pk=p)
                l = [prod.base_unit.pk, prod.sales_unit.pk, prod.control_unit.pk, prod.purchase_unit.pk, prod.taxed_unit.pk]
                l = list(set(l))
                qs = qs.filter(pk__in=l)
                #set(chain(Unit.on_company.all().values_list('id', flat=True), l))
            if q:
                qs = self.lookup_filter(qs, q)
            qs, more = self.paginate(qs, page, page_limit)

        return HttpResponse(json.dumps({
            'results': [self.format_object(obj) for obj in qs],
            'more': more,
        }), content_type='application/json')

templates/catalogue/itemcategory_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}
{% load crispy_forms_tags %}

{% block content %}
<div class="portlet light bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body form">
        {% crispy form %}
    </div>
</div>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
<script src={% static "assets/pages/scripts/form-samples.min.js" %} type="text/javascript"></script>
{% endblock %}

templates/catalogue/itemcategory_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}

{% block content %}
<!-- Begin: life time stats -->
<!-- Begin: life time stats -->
<div class="portlet light portlet-fit portlet-datatable bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body">
        <div class="table-container">
            <div class="table-actions-wrapper">
                <span>
                </span>
                <div class="actions">
                    <a href="{% url 'itemcategory:create' %}" class="btn btn-sm btn-info">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar Categoria </span>
                    </a>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover" id="default_datatable" ajax-url="{% url 'itemcategory:list-json' %}">
            <thead>
                <tr role="row" class="heading">
                    <th width="1%">#</th>
                    <th>Código</th>
                    <th>Descrição</th>
                    <th width="5%"></th>

                </tr>
            </thead>
            <tbody>
            </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End: life time stats -->
{% endblock content %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/datatables/datatables.min.css" %} rel="stylesheet" type="text/css" />
<link href={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
{% endblock %}

templates/catalogue/product_form.html
{% extends "base.html" %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load dictionary %}
{% block content %}
{#<div class="tab-pane">#}
    <div class="portlet light bordered">
        <div class="portlet-title tabbable-line">
            <div class="caption">
                <i class="icon-basket"></i>
                {% if object.id %}
                <span class="caption-subject font-blue-ebonyclay sbold">Atualizar Produto #{{ object.code }} | {{ object.description }}</span>
                {% else %}
                <span class="caption-subject font-blue-ebonyclay sbold">Cadastro de Produto </span>
                {% endif %}
            </div>
                <ul class="nav nav-tabs">
                    {% if object.id %}
                    <li class="{{ active|get_item:'formset_pricing' }}">
                        <a href="#portlet_tab_pricing" data-toggle="tab"> Tabela de Preços </a>
                    </li>
                    <li class="{{ active|get_item:'formset_suppliers' }}">
                        <a href="#portlet_tab_suppliers" data-toggle="tab"> Fornecedores </a>
                    </li>
                    {% endif %}
                    <li class="{{ active|get_item:'form' }}">
                        <a href="#portlet_tab_general" data-toggle="tab"> Informações Gerais </a>
                    </li>
                </ul>
        </div>
        <div class="portlet-body form">
            <form method="post" >
                <div class="tab-content">
                    <div class="tab-pane {{ active|get_item:'form' }}" id="portlet_tab_general">
                        {% crispy form %}
                    </div>
                    {% if object.id %}
                    <input type="hidden" value="{{ object.id }}" id="product_id">
                    <div class="tab-pane {{ active|get_item:'formset_suppliers' }}" id="portlet_tab_suppliers">
                        {{ formset_suppliers.management_form }}
                        <h4 class="form-section">Listagem de Fornecedores</h4>
                        <div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
                            <a id="tab_images_uploader_pickfiles" href="javascript:;" class="btn btn-success add-supplier">
                            <i class="fa fa-plus"></i> Incluir Fornecedor</a>
                        </div>
                        <div class="row"><div id="tab_images_uploader_filelist" class="col-md-6 col-sm-12"></div></div>
                        {% include 'metronic/table_inline_formset_nextify.html' with formset=formset_suppliers helper=suppliers_helper %}
                    </div>
                    <div class="tab-pane {{ active|get_item:'formset_pricing' }}" id="portlet_tab_pricing">
                        {{ formset_pricing.management_form }}
                        <h4 class="form-section">Tabelas de Preço</h4>
                        <div id="tab_images_uploader_container" class="text-align-reverse margin-bottom-10">
                            <a id="tab_images_uploader_pickfiles" href="javascript:;" class="btn btn-success add-pricetable">
                            <i class="fa fa-plus"></i> Incluir Tabela</a>
                        </div>
                        <div class="row"><div id="tab_images_uploader_filelist" class="col-md-6 col-sm-12"></div></div>
                        {% include 'metronic/table_inline_formset_nextify.html' with formset=formset_pricing helper=pricing_helper %}
                    </div>
                    {% endif %}
                </div>
                <div class="form-actions">
                    <div class="row">
                        <div class="col-md-6">
                            <div class="row">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="submit" name="submit" value="Salvar" class="btn btn-primary btn green" id="submit-id-submit"/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6"></div>
                </div>

            </form>
        </div>
    </div>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
<script src={% static "assets/pages/scripts/form-samples.min.js" %} type="text/javascript"></script>
<script src={% static "assets/apps/nextify/scripts/ncm/ncm.js" %} type="text/javascript"></script>
<script src={% static "assets/apps/nextify/scripts/catalogue/product.js" %} type="text/javascript"></script>
    {% if object.id %}
    <script type="text/html" id="supplier_template">
    {% include 'metronic/table_inline_formset_nextify_empty.html' with form=formset_suppliers.empty_form helper=suppliers_helper %}
    </script>

    <script type="text/html" id="pricing_template">
    {% include 'metronic/table_inline_formset_nextify_empty.html' with form=formset_pricing.empty_form helper=pricing_helper %}
    </script>
{% endif %}
{% endblock %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/select2/select2.css" %} rel="stylesheet" type="text/css"/>
<link href={% static "assets/global/plugins/select2/select2-bootstrap.css" %} rel="stylesheet" type="text/css"/>
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script type="text/javascript" src={% static "assets/global/plugins/select2/select2.min.js" %}></script>
{% endblock %}

templates/catalogue/product_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load sitetree %}
{% block content %}
<!-- Begin: life time stats -->
<div class="portlet light portlet-fit portlet-datatable bordered">
    {% sitetree_portlet from "maintree" %}
    <div class="portlet-body">
        <div class="table-container">
            <div class="table-actions-wrapper">
                <span>
                </span>
                <div class="actions">
                    <a href="{% url 'product:create' %}" class="btn btn-sm btn-info">
                        <i class="fa fa-plus"></i>
                        <span class="hidden-xs"> Cadastrar Produto </span>
                    </a>
                </div>
            </div>
            <table class="table table-striped table-bordered table-hover" id="default_datatable" ajax-url="{% url 'product:list-json' %}">
            <thead>
                <tr role="row" class="heading">
                    <th width="1%">#</th>
                    <th width="15%">Código</th>
                    <th>Descrição</th>
                    <th>Quantidade em Estoque</th>
                    <th>Valor de Venda</th>
                    <th width="5%"></th>

                </tr>
                <tr role="row" class="filter">
                    <td></td>
                    <td><input type="text" class="form-control form-filter input-sm" name="product_code"></td>
                    <td><input type="text" class="form-control form-filter input-sm" name="product_description"></td>
                    <td></td>
                    <td></td>
                    <td>
                        <div class="margin-bottom-5">
                            <button class="btn btn-sm btn-success filter-submit margin-bottom">
                                <i class="fa fa-search"></i> Pesquisar</button>
                        </div>
                        <button class="btn btn-sm btn-default filter-cancel"><i class="fa fa-times"></i> Limpar</button>

                    </td>

                </tr>
            </thead>
            <tbody>
            </tbody>
            </table>
        </div>
    </div>
</div>
<!-- End: life time stats -->
{% endblock content %}

{% block PAGE_LEVEL_PLUGINS_CSS %}
<link href={% static "assets/global/plugins/datatables/datatables.min.css" %} rel="stylesheet" type="text/css" />
<link href={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css" %} rel="stylesheet" type="text/css" />
{% endblock %}

{% block PAGE_LEVEL_PLUGINS %}
<script src={% static "assets/global/plugins/js.cookie.min.js" %} type="text/javascript"></script>
<script src={% static "assets/global/scripts/datatable_custom.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/datatables.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js" %} type="text/javascript"></script>
<script src={% static "assets/global/plugins/bootstrap-maxlength/bootstrap-maxlength.min.js" %} type="text/javascript"></script>
{% endblock %}

{% block PAGE_LEVEL_SCRIPTS %}
{% endblock %}